services:
  frontend:
    container_name: real-estate
    build:
      context: ./
      target: production
    restart: always
    environment:
      - NODE_ENV=production
  #   ports:
#      - "3001:3000"  # Uncommented for external access

networks:
  default:
    name: nginx-proxy-manager
    external: true
