import type { Metadata } from "next";
import { Poppins, Libre_Baskerville, Wix_Madefor_Display } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import { Footer } from "@/sections";

const libreBaskerville = Libre_Baskerville({
    variable: "--font-libre-baskerville",
    subsets: ["latin"],
    weight: ["400", "700"],
})


const poppins = Poppins({
    variable: "--font-poppins",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    subsets: ["latin"],
})

const madefor_display = Wix_Madefor_Display({
    variable: "--font-madefor-display",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700", "800"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${madefor_display.variable} ${poppins.variable} ${libreBaskerville.variable} antialiased`}
      >
        <Nav />
            {children}
        <Footer />
      </body>
    </html>
  );
}
